language: node_js
node_js:
- '5'
branches:
  except:
  - gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_12406b4b1545_key -iv $encrypted_12406b4b1545_iv
  -in id_rsa.enc -out id_rsa -d
deploy:
  # keep the build we just made with "npm test" (dist/)
  skip_cleanup: true

  # define the script to use for deployment
  provider: script
  script: npm run gh-pages-travis
env:
  global:
  - SSH_KEY="id_rsa"
  - GIT_NAME="Stewart Duffy"
  - GIT_EMAIL="duffy.stewart@gmail.com"
  - SOURCE_DIR="dist"
  - DEPLOY_BRANCH="master"
