language: node_js
node_js:
- '5'
branches:
  except:
  - gh-pages
after_sucess:
- npm run gh-pages-travis
env:
  global:
  - SSH_KEY="id_rsa"
  - GIT_NAME="Stewart Duffy"
  - GIT_EMAIL="duffy.stewart@gmail.com"
  - SOURCE_DIR="dist"
  - DEPLOY_BRANCH="master"
